// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Backend.Data;

namespace Project_Backend.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20210428131144_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project_Backend.Models.Director", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Age")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            ID = new Guid("4cb2fbc9-7a84-43ad-af49-a15dae7b4506"),
                            Age = 25m,
                            LastName = "Spielberg",
                            Name = "Steven"
                        },
                        new
                        {
                            ID = new Guid("071e2e1a-f7f0-47dc-a653-3fe758724554"),
                            Age = 50m,
                            LastName = "Nolan",
                            Name = "Christopher"
                        });
                });

            modelBuilder.Entity("Project_Backend.Models.DirectorMovies", b =>
                {
                    b.Property<Guid>("DirectorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieID")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("DirectorMovies");
                });

            modelBuilder.Entity("Project_Backend.Models.Movies", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            ID = new Guid("3eae78a9-8d42-4d18-8074-46df1531c9c5"),
                            DirectorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Genre = "Romance",
                            Name = "Titanic",
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("f11bf32c-e978-4c39-a310-5d780505e791"),
                            DirectorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Genre = "Sci-Fi",
                            Name = "The Martian",
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
